### ISSUE TITLE
[JavaScript] Highlight function parameters

### ISSUE THREAD

**Issue by B2o5T** [EvgeniyPeshkov/syntax-highlighter#11]
Did this extension solves this problem ? https://github.com/microsoft/vscode/issues/69824

**Comment by EvgeniyPeshkov** [comment]
Yes, sure:
![image](https://user-images.githubusercontent.com/50870158/58671211-69f51a00-834a-11e9-89e7-be7dc2ecffd1.png)

**Comment by EvgeniyPeshkov** [comment]
Making this screenshot, I've found a bug in TypeScript and Javascript highlighting. It'll be fixed in tomorrow's release.

**Comment by B2o5T** [comment]
Oh Jesus! Thank you, finally I will be able move to VSCode after this update
Спасибо Евгений ! ;)

**Comment by EvgeniyPeshkov** [comment]
Не за что )))

**Comment by EvgeniyPeshkov** [comment]
Hello @B2o5T , I've published the new version. 
You can install it as usual. TypeScript and JavaScript are fixed.

**Comment by B2o5T** [comment]
Hi @EvgeniyPeshkov, I have installed 0.2.7 version. But I don't see any changes, did I miss something? 
<img width="408" alt="image" src="https://user-images.githubusercontent.com/7361780/58741591-f66f0d80-841a-11e9-9870-5abd910c45bd.png">
I expected to see function parameters have a different color than variables as in WebStorm
<img width="379" alt="image" src="https://user-images.githubusercontent.com/7361780/58741611-5960a480-841b-11e9-90c0-110108927316.png">

**Comment by EvgeniyPeshkov** [comment]
Oh... It seems I've misled you. Look at the very first answer. I thought you wanted all variables to be highlighted the same way. It's exactly what {Syntax Highlighter} does. But you were asking about all appearances of function's parameter to be highlighted not the same way as local variables.
I'm afraid *tree-sitter* cannot handle this. Being just syntax analyzer, it doesn't track source of underling terms, it's task for language servers. Main idea behind {Syntax Highlighter} is to provide consistent, calm and neat colorization. Therefore we highlight all variables the same way, either they're local, global, static, members or parameters.
I'm very sorry for this misunderstanding.
