### ISSUE TITLE
[C/C++] Member access highlighting

### ISSUE THREAD

**Issue by alekseyt** [EvgeniyPeshkov/syntax-highlighter#13]
This is a question.

Is member access highlighting something tree-sitter can do? Like this:

![image](https://user-images.githubusercontent.com/993454/58713429-3c9c8080-83cb-11e9-87e1-92edd87239ad.png)

Note that `z`, `y`, `x` and `w` are highlighted in blue.

Example code:

```c++
b_ptr->z->y.x->w = 12.5f - 11 + 10.0;
```

**Comment by EvgeniyPeshkov** [comment]
You mean highlight local variables and members differently? Right?

**Comment by alekseyt** [comment]
Simply putting yes, i mean parts after '->' and '.' that highlighted in blue on screenshot. This indicates that it's a member variable. Original object being accessed is colored differently indeed.

**Comment by EvgeniyPeshkov** [comment]
There are several reasons.
* What if the most outer object `b_ptr` is in turn member. Then it's not obvious how to highlight it, like a member, or like a local variable. Being just syntax parser, tree-sitter cannot distinguish them.
* Why highlight `b_ptr` differently? Maybe it's better to give preference to `w`, as the last property in the chain.
* For example, for me it's more comfortable and simply enough to highlight all variables as variables and all functions as functions. I do not follow idea "more colors - better'.

**Comment by alekseyt** [comment]
OK, thanks, i'm closing this issue then.
