### ISSUE TITLE
[C++] Exceptions

### ISSUE THREAD

**Issue by alekseyt** [EvgeniyPeshkov/syntax-highlighter#15]
Example code:

```c++
#include <stdexcept>
#include <iostream>

int main() {
	const std::string message = "sup";

	try {
		throw std::runtime_error(message);
	}
	catch (const std::exception &e) {
		std::cout << e.what() << std::endl;
	}

	return 0;
}
```

Screenshot:

![image](https://user-images.githubusercontent.com/993454/58715435-85eecf00-83cf-11e9-9003-67585b7340d9.png)

Note that 

1) `throw` is not a keyword
2) `message` in `std::runtime_error(message)` is highlighted in cyan for some reason (i have cyan assigned to `syntax.type`)
3) `::` in `std::runtime_error` is highlighted differently from `::` in `std::string` or `std::cout`

Is this related to upstream tree-sitter or to this extension?

I've also tried to add `throw` to keywords:

```diff
         "\"try\"": "control",
+        "\"throw\"": "control",
         "\"catch\"": "control",
```

but this doesn't help.

Any ideas?

**Comment by EvgeniyPeshkov** [comment]
Hello @alekseyt , welcome to {Syntax Highlighter}.
I'm afraid *tree-sitter* cannot handle `throw` statements properly. It's a bug in tree-sitter.
I do not use exceptions at all, so I had no chance to check this.
*Tree-sitter* takes them for in-code declaration of function. In other words, the next two statements are syntactically the same:
`throw std::runtime_error(message);` vs `Type function(int);`
The same happens with construction of variable as we have discussed in [other issue](https://github.com/EvgeniyPeshkov/syntax-highlighter/issues/3#issuecomment-496026803). `Class variable(parameter);`. But in the later case we can think of constructors as special functions, that have the same name as class.

**Comment by alekseyt** [comment]
>the next two statements are syntactically the same

Except `throw` is a keyword. But whatever, if it's an issue in tree-sitter then i'm closing this one.

**Comment by EvgeniyPeshkov** [comment]
I meant, the same for tree-sitter, of course (=.
I collect such issues and intend to address them to tree-sitter community one day.
Maybe in future they'll fix these issues.

**Comment by EvgeniyPeshkov** [comment]
Hi @alekseyt ,
I just wanted to let you know, that the latest version of *tree-sitter-cpp* fixes this issue.
I'll publish an update in a day.
![image](https://user-images.githubusercontent.com/50870158/59506944-366dd000-8eb2-11e9-8b0f-b1239e79a14a.png)
