### ISSUE TITLE
Screenshots please

### ISSUE THREAD

**Issue by falconair** [EvgeniyPeshkov/syntax-highlighter#18]
Please post some screenshots of examples of highlighted syntax. From what I recall of syntax-highlighter, it is much more intelligent than simple token based parsers and should produce a much nicer (and more consistent) highlights. It'll be nice to be able to quickly view that. 

I'm thinking of showing this extension to my students and it will be nice for them to see if it is worth installing (most of them are comfortable with programming yet)

**Comment by EvgeniyPeshkov** [comment]
Hello @falconair , welcome.
You are right, I should include some demonstration/preview.
I just had no time for this. Will try to provide a demo as soon as possible.
Thank you.

**Comment by EvgeniyPeshkov** [comment]
Hello @falconair ,
I've added an animated gif demo. For now C++, Python and TypeScript are included in preview.
