### ISSUE TITLE
[All] Missing refresh?

### ISSUE THREAD

**Issue by Geobert** [EvgeniyPeshkov/syntax-highlighter#19]
I'm using auto formatter on save and sometime I got this kind of artefacts:

![image](https://user-images.githubusercontent.com/72570/58760312-fc094800-852d-11e9-905a-baff64276879.png)
 (look at `get_connection` bottom right of the screenshot)
And this one happened when I refactored the name of a variable

**Comment by EvgeniyPeshkov** [comment]
Hello @Geobert ,
You are right. I've also noticed similar behavior, as well as some other users.
To be precise, the root cause of this is multi-line edit.
I'll address this bug as soon as I can. Thank you.

**Comment by EvgeniyPeshkov** [comment]
This bug is fixed in the latest version.
