### ISSUE TITLE
Highlight corrupt after formatting

### ISSUE THREAD

**Issue by whoiscc** [EvgeniyPeshkov/syntax-highlighter#20]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/35130945/58879001-367a0d00-8707-11e9-8a0f-b9d9765da952.gif)

**Comment by EvgeniyPeshkov** [comment]
Hi @whoiscc , thank you for feedback.
I'm aware of this bug. It's already tracked in #19 .
I'll mark this one as duplicate and close. Stay tuned.

**Comment by EvgeniyPeshkov** [comment]
Hello @whoiscc ,
This bug is fixed in the latest version.

**Comment by whoiscc** [comment]
Got it. Thank you for your excellent development!

**Comment by EvgeniyPeshkov** [comment]
You're welcome (=
