### ISSUE TITLE
[C++] __attribute__ highlighting

### ISSUE THREAD

**Issue by bbatliner** [EvgeniyPeshkov/syntax-highlighter#21]
There seem to be some inconsistencies that appear when `__attribute__` is used on a struct:

```
struct __attribute__((packed)) struct1_t {
	static constexpr int A 	= 1;
	static constexpr int B	= 2;
	static constexpr int C	= 3;
};

struct struct2_t {
    static constexpr int A 	= 1;
	static constexpr int B	= 2;
	static constexpr int C	= 3;
};
```
![image](https://user-images.githubusercontent.com/5896658/59443860-5920bb80-8dc2-11e9-98ad-43284f8844cd.png)

The `static` modifiers are highlighted differently - do you know why?

**Comment by EvgeniyPeshkov** [comment]
Hi @bbatliner ,
It's the same situation as in #23 . I will try to fix this, but it may take some time.

**Comment by bbatliner** [comment]
`__attribute__` correctly highlights for functions and doesn't corrupt the tree. I'm seeing the same issue for structs, however.

![image](https://user-images.githubusercontent.com/5896658/59609299-c68f5d80-90dc-11e9-9bfd-3fed851bd06a.png)

Is this the intended behavior for now?

**Comment by EvgeniyPeshkov** [comment]
You are right. As I posted in #23 :
> `throw` and `virtual` have been fixed indeed. But highlighting of structs with `__attribute__` is still corrupted, it became slightly better though. It seems, that attributes are fixed only for functions in tree-sitter-cpp. So let's leave #21 open for a while. I'll try to ask *tree-sitter-cpp* developers to fix this issues.

But I was wrong, that it became slightly better =).
So we are waiting until `__attribute__` is fixed in *tree-sitter-cpp* for structs.
