### ISSUE TITLE
[C++] Macro and namespace oddities

### ISSUE THREAD

**Issue by bbatliner** [EvgeniyPeshkov/syntax-highlighter#22]
When using macros to define namespaces, some weird things happen:

```
#define OPEN_BRACE namespace a {
#define CLOSE_BRACE }

OPEN_BRACE

namespace b { namespace c { namespace d {

CLOSE_BRACE // d
CLOSE_BRACE // c
} // b
} // a
```
![image](https://user-images.githubusercontent.com/5896658/59444129-ec59f100-8dc2-11e9-918b-0f832162d5d9.png)

The first `namespace` keyword is highlighted differently than the others. Additionally, the two macros at the end are highlighted differently. Do you know why?

Thanks for your work on this extension! It works the best of any I've tried so far.

**Comment by EvgeniyPeshkov** [comment]
Hello @bbatliner , welcome. Thank you for the feedback.
{Syntax Highlighter} is based on Tree-sitter parser. Being just syntax parser, it doesn't track what's beneath macros, this is a task for a language server. So it doesn't expand them and cannot recover syntax tree if key terms like braces are embedded into the macro. In such cases syntax tree is corrupted from parser's point of view.

**Comment by EvgeniyPeshkov** [comment]
Hello @bbatliner ,
Don't you mind if we close this issue? I'm afraid, neither *tree-sitter* nor do I will be able to manage such cases.

**Comment by bbatliner** [comment]
Yeah, seems to be the case. I'll open a follow-up question in a different issue.
