### ISSUE TITLE
[C++] Virtual function oddities

### ISSUE THREAD

**Issue by bbatliner** [EvgeniyPeshkov/syntax-highlighter#23]
I can't explain what's going on here: the highlighting changes vastly despite the function signatures being nearly identical. The presence of the `virtual` keyword seems to play an effect. In this example, the first function has incorrect/inconsistent highlighting, and the second is highlighted as expected.

![image](https://user-images.githubusercontent.com/5896658/59446811-d1d64680-8dc7-11e9-9bf0-9baa517ffc07.png)

**Comment by bbatliner-ocient** [comment]
I think adding `virtual` as a `modifier` will solve these problems. I don't see it in the cpp grammar file.

**Comment by bbatliner** [comment]
I think adding `virtual` as a `modifier` will solve this issue. I don't see it in the cpp grammar. I'll make a PR on Github but I can't really test it.

**Comment by EvgeniyPeshkov** [comment]
Hello @bbatliner ,
In fact it's a bug in *tree-sitter-cpp*, that incorrectly parses definitions with `virtual`.
I've just discovered, that there's a newer version, maybe it's already fixed. Otherwise I'll upstream corresponding question to *tree-sitter-cpp* developers. Anyway, there's another bug with `default`.
Yet you are right that `virtual` is missing. I'll merge your PR. Please note, that it won't fix the issue.

**Comment by EvgeniyPeshkov** [comment]
Hello @bbatliner ,
It seems I was right, the latest version of *tree-sitter-cpp* fixes at least this issue.
I'll publish a new version in a day. Stay tuned.
![image](https://user-images.githubusercontent.com/50870158/59506399-bd21ad80-8eb0-11e9-9aa1-08bc8f5d40a9.png)

**Comment by bbatliner** [comment]
Awesome, that's great to hear. It looks like `throw` and maybe `__attribute__` got added to that latest version, as well. We might be able to close #21, if it fixes that, too.

**Comment by EvgeniyPeshkov** [comment]
`throw` and `virtual` have been fixed indeed. But highlighting of structs with `__attribute__` is still corrupted, it became slightly better though. It seems, that attributes are fixed only for functions in *tree-sitter-cpp*. So let's leave #21 open for a while. I'll try to ask *tree-sitter-cpp* developers to fix this issues.

**Comment by EvgeniyPeshkov** [comment]
Hello @bbatliner , just in case, 
this bug is fixed in the latest version 0.3.3, I've published on Friday.

**Comment by bbatliner** [comment]
Yes, confirmed. Thanks.
