### ISSUE TITLE
[Rust] async/await not coloured correctly

### ISSUE THREAD

**Issue by hackerer1c** [EvgeniyPeshkov/syntax-highlighter#28]
<img width="418" alt="屏幕快照 2019-07-08 上午9 39 12" src="https://user-images.githubusercontent.com/18899791/60777525-751b4100-a165-11e9-958d-233b19c4093d.png">

In this picture, `async` block is coloured as struct constructor (just as `Metadata` does), and `.await` is coloured as struct field.

**Comment by EvgeniyPeshkov** [comment]
Hello @hackerer1c ,
Could you kindly provide source code. It's better to include surrounding context, at least the whole function.
