### ISSUE TITLE
[Rust] $1 coloured as type in `use $1::$2`

### ISSUE THREAD

**Issue by hackerer1c** [EvgeniyPeshkov/syntax-highlighter#29]
<img width="428" alt="屏幕快照 2019-07-08 上午9 36 27" src="https://user-images.githubusercontent.com/18899791/60777698-61240f00-a166-11e9-914f-9baffb47909d.png">

`bytes` and `data_encoding` are coloured the same as `Bytes` and `BASE64URL_NOPAD`.

**Comment by EvgeniyPeshkov** [comment]
Hello @hackerer1c , thank you for the feedback.
I've fixed this issue. New version will be available soon.
![image](https://user-images.githubusercontent.com/50870158/60992062-7068af80-a354-11e9-992d-d1ac05852634.png)

**Comment by EvgeniyPeshkov** [comment]
The latest version is available in the Marketplace. So I'll close this issue.
