### ISSUE TITLE
Problems with Python highlighting

### ISSUE THREAD

**Issue by chinalufei** [EvgeniyPeshkov/syntax-highlighter#31]
If my code contains the following code snippets
print(f"{aa:#x}")
It seems that Python 3.6 f-string is not well supported

**Comment by EvgeniyPeshkov** [comment]
Hello @chinalufei ,
You are right, *tree-sitter-python* currently has a problem with f-strings, even in latest version from npm. The good news is [this PR](https://github.com/tree-sitter/tree-sitter-python/pull/33) seems to fix it. It's not in package registry yet, I'll try to build parser from *master*. If it really helps, I'll update and upload new version of extension.

**Comment by EvgeniyPeshkov** [comment]
Unfortunately, no luck. The latest *master* version cannot handle such expression either.
The problem is `#` inside interpolation is not treated properly. I've submitted [corresponding issue](https://github.com/tree-sitter/tree-sitter-python/issues/49) to *tree-sitter-python*.

**Comment by blipk** [comment]
@EvgeniyPeshkov 
Any change of revisiting this? It looks like the PR in tree-sitter is has been merged.

I'd like to get better highlighting support for f-strings.

I tried editing my settings.json by setting the semanticTokenColorCustomizations for string foreground to nothing and then setting the appropriate textMateRules scopes but this only highlights them the blue I've set for a moment and then they reset.

```json
    "editor.semanticTokenColorCustomizations": {
        "enabled": true,
        "rules": {
            "string": {
                "foreground": ""
            },
        }
    },
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": ["meta.function-call.python"],
                "settings": {
                    // "foreground": "#bf0f0f" 
                }
            },
            {
                "scope": [
                    "meta.fstring.python",
                    //"string.quoted.single.python",
                    //"string.quoted.double.python",
                    //"string.interpolated.python",
                ],
                "settings": {
                    "foreground": "#210fbf"
                }
            },
        ],
    },
```

Any pointers on how I can set my colors for the varying textmate scopes? Or is it possible with this extension?

**Comment by chinalufei** [comment]
您好！您的邮件已收到！非常感谢您的来信......
