### ISSUE TITLE
C++ keywords int 、long、... are overwritten

### ISSUE THREAD

**Issue by chinalufei** [EvgeniyPeshkov/syntax-highlighter#32]
![image](https://user-images.githubusercontent.com/13611195/62751541-b1103180-ba96-11e9-9393-bc7c443c5444.png)
![image](https://user-images.githubusercontent.com/13611195/62751561-c2593e00-ba96-11e9-9627-791082677a1d.png)
I want to configure the color of keywords。

**Comment by EvgeniyPeshkov** [comment]
Hello @chinalufei ,
{Syntax Highlighter} colorizes all types (fundamental like `int` or custom like `SomeClass`) the same way.
In my opinion this provides clean, neat and calm syntax highlighting. Please, refer [this answer](https://github.com/EvgeniyPeshkov/syntax-highlighter/issues/6#issuecomment-496578112) for example.
