### ISSUE TITLE
Extension crashes when used with local-history

### ISSUE THREAD

**Issue by malte-v** [EvgeniyPeshkov/syntax-highlighter#34]
Unfortunately these two extensions seem to be incompatible. The highlighter extension crashes when I'm starting to edit a file (I have auto-save set to `true`).

**Comment by EvgeniyPeshkov** [comment]
Hello @malte-v ,
Thank you for the feedback. I'll see what I can do and return to you asap.

**Comment by EvgeniyPeshkov** [comment]
Hello @malte-v .
I cannot reproduce this issue.
If you still experience crashes, please reopen it.
Regards.
