### ISSUE TITLE
Language Request: Shellscript/bash

### ISSUE THREAD

**Issue by FSciammarella** [EvgeniyPeshkov/syntax-highlighter#35]
Hello,

I would like to vouch for the inclusion of shellscript/bash support, as VSCode uses Textamate's outdated and very crude grammar.

Thanks for your awesome work on C++.

**Comment by EvgeniyPeshkov** [comment]
Hello, @FSciammarella.
Thank you very much for the feedback.
I think it's possible to include shellscript support.
It'll take couple of days. Stay tuned.

**Comment by EvgeniyPeshkov** [comment]
Support of ShellScript/Bash has been added to the latest version, already available at VSCode Marketplace. I'm not very good at bash, so I believe there are inaccuracies that need to be fixed or improved. Please, do not hesitate to open further issues if you find anything.
