### ISSUE TITLE
Mapping for Noctis

### ISSUE THREAD

**Issue by khuongduybui** [EvgeniyPeshkov/syntax-highlighter#36]
Hi, Noctis is the top trending / popular set of themes for VS Code at the moment.
They list the following colors in their palettes:

- Strings
- Interpolated Strings
- Comments
- Function Calls
- Method Calls
- Code that needs to stand out
- Numbers & Booleans
- Keywords & Operators
- Function & Variable Declaration, Tags & this
- Object properties, ID selectors in CSS & Type annotations
- Attributes, Constants
- Variables & Parameters

What is the best mapping settings to put in `workbench.colorCustomization`?

**Comment by EvgeniyPeshkov** [comment]
Hello @khuongduybui .
If you would like to adjust syntax highlighter to follow these themes, I think you need to use something like:
```json
"workbench.colorCustomizations": {
    "[Noctis]": {
        "syntax.type": "Code that needs to stand out",
        "syntax.scope": "Code that needs to stand out",
        "syntax.function": "Function Calls or Method Calls",
        "syntax.variable": "Variables & Parameters or Attributes, Constants or Object properties",
        "syntax.number": "Numbers & Booleans",
        "syntax.string": "Strings",
        "syntax.comment": "Comments",
        "syntax.constant": "Numbers & Booleans",
        "syntax.directive": "Keywords & Operators",
        "syntax.control": "Keywords & Operators",
        "syntax.operator": "Keywords & Operators",
        "syntax.modifier": "Keywords & Operators",
        "syntax.punctuation": "#A1887F",
    }
},
```
I'm not sure what color to advice for punctuation, as Noctis doesn't mention it.
Also, they do not separate keywords between operators, control flow, modifiers, etc.
In turn SyntaxHighlighter do not member methods/properties and global functions/variables differently, so you can choose any corresponding color from Noctis you like.
