### ISSUE TITLE
Interference with bracket pair colorizer

### ISSUE THREAD

**Issue by DusterTheFirst** [EvgeniyPeshkov/syntax-highlighter#39]
Just what it says in the title. The colors from BPC are not shown.

**With syntax-highlighter**
![image](https://user-images.githubusercontent.com/14093962/70959381-1ded9680-204a-11ea-963d-2eae6dac2338.png)

**Without syntax-highlighter**
![image](https://user-images.githubusercontent.com/14093962/70959428-41b0dc80-204a-11ea-9823-fe7558686b56.png)

**Comment by EvgeniyPeshkov** [comment]
Hello @DusterTheFirst .
In the latest version there is an option to enable/disable highlighting of syntax terms.
You can set `syntax.highlightTerms` in *settings.json* and remove `punctuation` from the list.
Then {Syntax Highlighter} will skip `punctuation` terms and won't override colorization provided by "Bracket Pair Colorizer".

**Comment by DusterTheFirst** [comment]
Thank you very much, that helped a lot!
