### ISSUE TITLE
Crashes frequently on macOS

### ISSUE THREAD

**Issue by thomcc** [EvgeniyPeshkov/syntax-highlighter#40]
I'm on macOS 10.14 and using this with rust and it crashes frequently. Almost immediately after starting -- it's basically unusable.

The error in the console can be seen here: https://gist.github.com/thomcc/1a5f90fc7e1263c82a5acae0e0311afc, let me know if I can help you further.

Note: I don't think this is related to #34 as I don't have that extension.

**Comment by nfour** [comment]
Same here, after a few moments it crashes.

Using SSH: Remote from Windows to an ArchLinux VM.

**Comment by EvgeniyPeshkov** [comment]
Hi, I've finally caught these crashes myself. Will try to fix it ASAP.

**Comment by Hunter-Guimont** [comment]
Extension host crashes on boot, only works if disabled then re-enabled mid session. On Arch Linux.
