### ISSUE TITLE
🎨 Diffrent `Syntax Highlighting` for each language... Is that possible?

### ISSUE THREAD

**Issue by rediffusion** [EvgeniyPeshkov/syntax-highlighter#42]
@EvgeniyPeshkov 

 ✌️ Привет! 
🔌 Интереснре расширение.

As an example, I'll take the IDE called «[NotePad++](https://notepad-plus-plus.org/downloads/)».
 _See screenshots below_:

![image](https://user-images.githubusercontent.com/30071027/71870673-e2fdf080-3127-11ea-8c28-428853d86fee.png)

Now I put here some `code`, then I switch to other languages...

## C#

![image](https://user-images.githubusercontent.com/30071027/71933856-2605a580-31b4-11ea-903e-b45e1b6573c9.png)

## JavaScript

![image](https://user-images.githubusercontent.com/30071027/71934009-8268c500-31b4-11ea-94f3-b53dbf21d421.png)

## AutoHotkey

![image](https://user-images.githubusercontent.com/30071027/71934110-c78cf700-31b4-11ea-935c-e5f74da6bfba.png)

## C++

![image](https://user-images.githubusercontent.com/30071027/71934169-ee4b2d80-31b4-11ea-8277-a71d5d36a757.png)

## CSS

![image](https://user-images.githubusercontent.com/30071027/71934273-25b9da00-31b5-11ea-93bf-65b363112661.png)

## HTML 

![image](https://user-images.githubusercontent.com/30071027/71934407-687bb200-31b5-11ea-9fc9-ce945acc25f0.png)

Different syntax, color, style, font, weight, brackets... etc.
But in your cool **extension** I see the same shit with all languages. Please help! 🙏

---

P.S. ··· read carefully this [manual](https://github.com/EvgeniyPeshkov/syntax-highlighter/blob/master/BUILD.md). Is this link valid? It's directing me to _GitHub's_ home page. "**Build:**". Please provide the relevant link!

> 1. Clone or download extension from [GitHub](https://github.com).

 Спасибо уважаемый! 🍻👍

**Comment by EvgeniyPeshkov** [comment]
Hello @rediffusion .

Thank you for noticing that build instructions are outdated. I've updated them. Please check out the latest version.

So you want extension to provide different highlighting (colors) depending on language. In simpler words: different languages - different colors. Right?

**Comment by rediffusion** [comment]
@EvgeniyPeshkov 

Good damn, YES!

**Comment by EvgeniyPeshkov** [comment]
Actually, the main purpose is quite opposite - consistent syntax highlighting across all languages. So you are not confused when switching between them. E.g. types are colored the same way whereever you go.
