### ISSUE TITLE
Ocaml support

### ISSUE THREAD

**Issue by hackwaly** [EvgeniyPeshkov/syntax-highlighter#43]
https://github.com/tree-sitter/tree-sitter-ocaml

**Comment by EvgeniyPeshkov** [comment]
Hello @hackwaly ,
It's almost ready, I'll publish the new version tomorrow.

**Comment by EvgeniyPeshkov** [comment]
OCaml is supported in the newest version available in VSCode Marketplace.
I am not familiar with Ocaml, so kindly give your feedback. Maybe there are some inaccuracies that can be fixed.
