### ISSUE TITLE
How to disable highlight for one specific language

### ISSUE THREAD

**Issue by maielo** [EvgeniyPeshkov/syntax-highlighter#47]
Hello, 

I would like to ask, if there is any way how to disable highliting for one specific language. I prefer the original one, but wanna keep this highlighting for rest.

**Comment by EvgeniyPeshkov** [comment]
Hello @maielo ,
There is [syntax.highlightLanguages](https://github.com/EvgeniyPeshkov/syntax-highlighter/blob/master/README.md#syntaxhighlightlanguages) config that can be tuned in `settings.json`. By default all supported languages are enabled, you just need to remove language in question from the list.

**Comment by maielo** [comment]
Thank you very much, i am not much familiar with editing extensions and how it works but i kinda figure it out. :)
