### ISSUE TITLE
support for bold and italics customization

### ISSUE THREAD

**Issue by mbsmith93** [EvgeniyPeshkov/syntax-highlighter#48]
Being able to set not just the color but also the italics or bold behavior of certain syntax terms would be great. If this is already possible it would be great if it could be added to the documentation, as I do not currently see any way to do this.

**Comment by EvgeniyPeshkov** [comment]
Hello @mbsmith93,
This is in fact easy to implement. But at the moment I'm planning to [adopt new *semantic highlighting api*](https://github.com/EvgeniyPeshkov/syntax-highlighter/issues/44#issuecomment-621424415). After that, extension will highlight tokens according to the current theme. This will automatically allow to decorate tokens whatever one likes, plus many other advantages. Stay tuned.
