### ISSUE TITLE
[Rust] () as punctuation instead of type in <>

### ISSUE THREAD

**Issue by Geobert** [EvgeniyPeshkov/syntax-highlighter#5]
![image](https://user-images.githubusercontent.com/72570/58467120-faf1a880-8132-11e9-81e0-d4dac0550fa4.png)

Here, `()` is a type (it's between `<>`) and coloured as punctuation

**Comment by EvgeniyPeshkov** [comment]
This is easy, it's done.
![image](https://user-images.githubusercontent.com/50870158/58471495-a9561780-814c-11e9-94cf-5586deac37e8.png)
May I ask you to post code itself alongside screenshot. At least for short examples. Or link to source file for long ones. It'll save a lot of time.

**Comment by Geobert** [comment]
Ok, let me update the other issues for you! :D
