### ISSUE TITLE
Highlight escape sequences in strings

### ISSUE THREAD

**Issue by JakobR** [EvgeniyPeshkov/syntax-highlighter#54]
Is it possible to highlight escape sequences in strings differently than the rest of the string? E.g., like this:

<img width="154" alt="Screenshot 2020-10-22 at 17 37 21" src="https://user-images.githubusercontent.com/1545558/96895965-4b3a7a80-148d-11eb-9f19-6a6fee5b4822.png">

I tried setting `constant.character.escape`, but this did not make a difference as far as I can tell.

**Comment by EvgeniyPeshkov** [comment]
Hello @JakobR !
Syntax Highlighter is designed to parse a source code at a slightly coarser scale. The smallest token is a syntax term. Such functionality will require additional parsing of individual tokens.
Kindly note that `constant.character.escape` is a rule for TextMate scopes, not Semantic Tokens.

**Comment by JakobR** [comment]
Hi, thanks for your answer! I see now that this is out of scope for this project.
