### ISSUE TITLE
Publish on Open-VSX

### ISSUE THREAD

**Issue by potter420** [EvgeniyPeshkov/syntax-highlighter#58]
Hi @EvgeniyPeshkov,

I am just wondering if this extension can be published on Open-VSX for usage in Code-Server/Theia IDE/ Eclipse Che environments. Since MS killed the self-hosted Github CodeSpace option, we currently looking at those as options to develop remotely without an SSH connections. 

For instance, Python without Pylance (which include semantic highlighting and is closed source) look terrible on alternatives.

Thank you very much.

**Comment by EvgeniyPeshkov** [comment]
Hello @potter420 !
Sure, I'll publish *syntax-highlighter* on Open-VSX ASAP.
I'll write here and close this issue when it's done.

**Comment by EvgeniyPeshkov** [comment]
It's done. Syntax Highlighter is now available on Open-VSX.
https://open-vsx.org/extension/evgeniypeshkov/syntax-highlighter

**Comment by potter420** [comment]
Wow, that was quick. Thank you and issue closed 👯‍♀️
