### ISSUE TITLE
[Rust] self is a keyword

### ISSUE THREAD

**Issue by Geobert** [EvgeniyPeshkov/syntax-highlighter#7]
![image](https://user-images.githubusercontent.com/72570/58468524-9ab03600-8135-11e9-8950-3a4bf3848d04.png)
Here, `self` is like a variable, but it's a keyword, equivalent to `this` in C++

**Comment by Geobert** [comment]
```rust
#[derive(Debug, Serialize, Deserialize)]
pub struct Token {
    pub session_token: String,
}

impl Deref for Token {
    type Target = String;

    fn deref(&self) -> &String {
        &self.session_token
    }
}
```

**Comment by EvgeniyPeshkov** [comment]
May I then highlight all occurrences of `self`, `super` and `crate` as *keyword_operator*, *keyword_constant*, or *keyword_directive*. I recommend you to choose *keyword_operator* or *keyword_constant* (=.

**Comment by Geobert** [comment]
I was thinking of `keywork_control` ^^'

**Comment by EvgeniyPeshkov** [comment]
Yep, *keyword_control* is also good. The point was, not to use *keyword_directive* ))).
