### ISSUE TITLE
[Rust] .. should be like operator

### ISSUE THREAD

**Issue by Geobert** [EvgeniyPeshkov/syntax-highlighter#8]
![image](https://user-images.githubusercontent.com/72570/58468697-f37fce80-8135-11e9-9b28-46771a38f529.png)

In Rust, you can define a range with `..` : `0..3` is 0 to 3 excluded and you can have `0..=3` meaning 3 included.

**Comment by EvgeniyPeshkov** [comment]
This is also ready.
![image](https://user-images.githubusercontent.com/50870158/58471734-3ac58980-814d-11e9-83f2-9a0c595f26c7.png)

**Comment by Geobert** [comment]
Does `..=` works as well?

**Comment by EvgeniyPeshkov** [comment]
Yes, it works as well. It seems to me, that Tree-sitter itself gets it wrong, but as `=` is also operator, highlighting is fine (=.
