### ISSUE TITLE
[Language Request] Lua

### ISSUE THREAD

**Issue by Stanzilla** [EvgeniyPeshkov/syntax-highlighter#9]
This should probably do? https://github.com/Azganoth/tree-sitter-lua

**Comment by EvgeniyPeshkov** [comment]
Hello @Stanzilla , welcome to {Syntax Highlighter}.
I'll see what I can do. It'll take several days. I will notify you  periodically about my progress.

**Comment by Stanzilla** [comment]
Awesome, thank you!

**Comment by EvgeniyPeshkov** [comment]
I think it'll be ready tomorrow, so stay tuned (=.

**Comment by EvgeniyPeshkov** [comment]
Hello @Stanzilla , I've finished preview support for Lua.
I would like to send you custom build of extension, so you can install it manually and try. Is it OK?
Or I can include it in a release, that I will publish tomorrow.

**Comment by Stanzilla** [comment]
Hey sure, can you upload the vsix somewhere?

**Comment by EvgeniyPeshkov** [comment]
Sure, I think I can upload it right here ))).
[syntax-highlighter-0.2.6-lua.zip](https://github.com/EvgeniyPeshkov/syntax-highlighter/files/3241825/syntax-highlighter-0.2.6-lua.zip)
Please, be aware that *tree-sitter-lua* is not very extensive. I've tried to do my best. Maybe there is something that still can be fixed, but I suppose not much.

**Comment by Stanzilla** [comment]
Looks pretty good so far! I might need to tweak the colors a bit, it's a bit too colorful for my liking, otherwise awesome job, thank you :)

**Comment by EvgeniyPeshkov** [comment]
You are welcome. (=
I'll let you know, when version with Lua is in Marketplace.

**Comment by Stanzilla** [comment]
https://i.imgur.com/dfh6zZg.png is a small bug I just found

**Comment by EvgeniyPeshkov** [comment]
Yes, you are right. I saw similar behavior. It happens sometimes, mostly when pasting a text or doing multi-line editing. I'll address this bug in near future. Thank you.

**Comment by EvgeniyPeshkov** [comment]
Hello @Stanzilla ,
I've published new version with Lua, so you can install it from Marketplace as usual. I think this issue may be closed.
As for sometimes broken highlighting, we'll track this bug in issue #19 .

**Comment by Stanzilla** [comment]
Awesome, thank you!
